export const OPPORTUNITY_DUMMY_DATA = [
  {
    _id: 'demo-job-1',
    type: 'job',
    title: 'Sugarcane harvesting labour needed',
    description:
      'Need 6 workers for sugarcane harvesting on 5 acres. Food included. Payment per day.',
    urgent: true,
    location: { text: 'Kolhapur, Maharashtra' },
    paymentType: 'per_day',
    amount: 650,
    workType: 'harvesting',
    workersRequired: 6,
    startDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    durationDays: 5,
    foodIncluded: true,
    stayIncluded: false,
    requirements: ['Sugarcane harvesting experience', 'Bring own gloves if possible'],
    images: [{ url: 'https://images.unsplash.com/photo-1592982537447-9fea6aff1093?w=1200&auto=format&fit=crop&q=80' }],
    ratingAverage: 4.6,
    ratingCount: 12,
    applicantsCount: 3,
    farmer: { _id: 'demo-owner-1', name: 'Shivaji Patil' },
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'demo-equip-1',
    type: 'equipment',
    title: 'Tractor with rotavator for rent',
    description:
      '55 HP tractor + rotavator available within 20km. Delivery possible. Fuel not included.',
    urgent: false,
    location: { text: 'Meerut, Uttar Pradesh' },
    rentalUnit: 'per_hour',
    amount: 900,
    securityDeposit: 2000,
    deliveryAvailable: true,
    fuelIncluded: false,
    equipmentName: 'Tractor + Rotavator',
    equipmentBrandModel: 'Mahindra 575 DI XP Plus',
    equipmentCondition: 'good',
    images: [{ url: 'https://images.unsplash.com/photo-1614358145930-2a892f54a5f0?w=1200&auto=format&fit=crop&q=80' }],
    ratingAverage: 4.9,
    ratingCount: 32,
    applicantsCount: 0,
    farmer: { _id: 'demo-owner-2', name: 'Kisan Tractor Service' },
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: 'demo-cattle-1',
    type: 'cattle',
    title: 'Pair of oxen for ploughing (day basis)',
    description:
      'Healthy and trained oxen available for traditional ploughing. Suitable for small farms.',
    urgent: false,
    location: { text: 'Hosapete, Karnataka' },
    pricePerDay: 700,
    animalType: 'ox',
    purpose: 'ploughing',
    vaccinated: true,
    ageYears: 6,
    healthCondition: 'Strong and healthy, regularly dewormed',
    images: [{ url: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=1200&auto=format&fit=crop&q=80' }],
    ratingAverage: 4.3,
    ratingCount: 8,
    applicantsCount: 1,
    farmer: { _id: 'demo-owner-3', name: 'Basavaraj Gowda' },
    createdAt: new Date(Date.now() - 28 * 60 * 60 * 1000).toISOString(),
  },
];

